<a href="https://colab.research.google.com/github/Gayatri925/AI-Powered-Workforce-Analytics-Talent-Intelligence-Dashboard/blob/main/SQLTasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**SQL Functions**

**Prompt:** A Python program to create an SQLite database, create an Employees table, insert employee records, and display the stored data using the Pandas DataFrame.

In [4]:

import sqlite3
import pandas as pd

# Create in-memory database
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

#create table
cursor.execute("""
  CREATE TABLE Employees(
    EmployeeID TEXT PRIMARY KEY,
    Age INTEGER,
    Department TEXT,
    Total_working_years INTEGER,
    PerformanceRating TEXT
)
""")

employees = [
    ("EMP001", 24, "IT", 2, 3),
    ("EMP002", 28, "HR", 5, 4),
    ("EMP003", 35, "Finance", 10, 5),
    ("EMP004", 30, "Sales", 7, 4),
    ("EMP005", 26, "Marketing", 4, 3),
    ("EMP006", 41, "IT", 18, 5),
    ("EMP007", 33, "HR", 9, 4),
    ("EMP008", 29, "Finance", 6, 3),
    ("EMP009", 45, "Operations", 22, 5),
    ("EMP010", 31, "Sales", 8, 4),
    ("EMP011", 27, "Marketing", 5, 3),
    ("EMP012", 39, "IT", 15, 5),
    ("EMP013", 36, "Finance", 12, 4),
    ("EMP014", 25, "HR", 3, 3),
    ("EMP015", 42, "Operations", 20, 5),
    ("EMP016", 34, "Sales", 11, 4),
    ("EMP017", 38, "Marketing", 14, 5),
    ("EMP018", 23, "IT", 1, 2),
    ("EMP019", 32, "Finance", 9, 4),
    ("EMP020", 40, "Operations", 17, 5)
]
cursor.executemany("INSERT INTO Employees VALUES (?,?,?,?,?)", employees)
conn.commit()

# Display data
df = pd.read_sql("SELECT * FROM Employees", conn)
df

   EmployeeID  Age  Department  Total_working_years PerformanceRating
0      EMP001   24          IT                    2                 3
1      EMP002   28          HR                    5                 4
2      EMP003   35     Finance                   10                 5
3      EMP004   30       Sales                    7                 4
4      EMP005   26   Marketing                    4                 3
5      EMP006   41          IT                   18                 5
6      EMP007   33          HR                    9                 4
7      EMP008   29     Finance                    6                 3
8      EMP009   45  Operations                   22                 5
9      EMP010   31       Sales                    8                 4
10     EMP011   27   Marketing                    5                 3
11     EMP012   39          IT                   15                 5
12     EMP013   36     Finance                   12                 4
13     EMP014   25          HR                    3                 3
14     EMP015   42  Operations                   20                 5
15     EMP016   34       Sales                   11                 4
16     EMP017   38   Marketing                   14                 5
17     EMP018   23          IT                    1                 2
18     EMP019   32     Finance                    9                 4
19     EMP020   40  Operations                   17                 5

**Prompt:** to display the total number of employees in the Employees table using the SQL COUNT() function.

In [ ]:
# Total Employees
print("Total Employees")
display(pd.read_sql("""
SELECT COUNT(*) AS TotalEmployees
FROM Employees
""", conn))

Total Employees

   TotalEmployees
0              20

**Prompt:** to calculate and display the average total working years of employees using the SQL AVG() function.

In [5]:
print("Average Experience")
display(pd.read_sql("""
SELECT ROUND(AVG(Total_working_years),2) AS AverageExperience
FROM Employees
""", conn))

Average Experience

   AverageExperience
0                9.9

**Prompt:** to display the number of employees in each department using the SQL COUNT() function and GROUP BY clause.

In [6]:
print("Department-wise Employee Count")
display(pd.read_sql("""
SELECT Department,
       COUNT(*) AS EmployeeCount
FROM Employees
GROUP BY Department
""", conn))

Department-wise Employee Count

   Department  EmployeeCount
0     Finance              4
1          HR              3
2          IT              4
3   Marketing              3
4  Operations              3
5       Sales              3

**Prompt:** to display the details of employees with a Performance Rating of 5 using the SQL WHERE clause.

In [8]:
print("Display Employees with Performance Rating is 5")
display(pd.read_sql("""
SELECT *
FROM Employees
WHERE PerformanceRating = 5
""",conn))

Display Employees with Performance Rating is 5

  EmployeeID  Age  Department  Total_working_years PerformanceRating
0     EMP003   35     Finance                   10                 5
1     EMP006   41          IT                   18                 5
2     EMP009   45  Operations                   22                 5
3     EMP012   39          IT                   15                 5
4     EMP015   42  Operations                   20                 5
5     EMP017   38   Marketing                   14                 5
6     EMP020   40  Operations                   17                 5